### ISSUE TITLE
[native]2.0.0-rc1 Roadmap

### ISSUE THREAD

**Issue by wenfengwang** [apache/rocketmq-client-go#120]
The 2.0.0-rc1 has been started, welcome anyone request for an unassigned item or have any contributions for us!

Duration
7.19-8.7（**delayed**）

Target
1. Improve stability and reliability
2. More Unit Test: 50% coverage
3. Remain features 
4. Optimize API & bugfix 

## Bugfix
- [x] https://github.com/apache/rocketmq-client-go/issues/135 bufio.Scanner: token too long
- [x] https://github.com/apache/rocketmq-client-go/issues/139  fatal error: concurrent map writes fixed at https://github.com/apache/rocketmq-client-go/pull/146
- [x] https://github.com/apache/rocketmq-client-go/issues/130 missing shutdown in PushConsumer  https://github.com/apache/rocketmq-client-go/pull/172
- [x] https://github.com/apache/rocketmq-client-go/issues/144 consumer examples run error  fixed at https://github.com/apache/rocketmq-client-go/pull/145
- [x] https://github.com/apache/rocketmq-client-go/issues/166 concurrent map read and map write on `message.Properties`  https://github.com/apache/rocketmq-client-go/pull/197

## Optimization
- [x] unified implementation of interceptor @gaufung  https://github.com/apache/rocketmq-client-go/pull/132
- [x] Optimize Pull API @wenfengwang  https://github.com/apache/rocketmq-client-go/issues/151
- [x] Go Context @xujianhai666 https://github.com/apache/rocketmq-client-go/pull/177
- [x] implement unpress func  https://github.com/apache/rocketmq-client-go/issues/164

## Features
- [x] Support full `AllocateStrategy` algorithm @luther-siyuan https://github.com/apache/rocketmq-client-go/pull/141
- [x] Support delay message @xujianhai666 https://github.com/apache/rocketmq-client-go/issues/122
- [x] Support message tracing @xujianhai666 https://github.com/apache/rocketmq-client-go/issues/124
- [x] Support Transaction message @xujianhai666  https://github.com/apache/rocketmq-client-go/pull/136
- [x] Support Namersrv domain @wenfengwang  https://github.com/apache/rocketmq-client-go/issues/147
- [x] Support multiple namespace @wenfengwang https://github.com/apache/rocketmq-client-go/issues/147
- [x] Support multiple namesrv cluster @xujianhai666 https://github.com/apache/rocketmq-client-go/issues/162 

## Unit Test
- [x] consumer/consumer.go @xujianhai666 https://github.com/apache/rocketmq-client-go/pull/179
- [x] consumer/offset_store.go @luther-siyuan https://github.com/apache/rocketmq-client-go/pull/141
- [ ] consumer/process_queue.go @gaufung 

~~consumer/pull_consumer.go @wenfengwang(move to v2.1.0)~~

- [x] consumer/push_consumer.go @cloes https://github.com/apache/rocketmq-client-go/pull/156
- [x] consumer/statistic.go @gaufung https://github.com/apache/rocketmq-client-go/issues/148
- [x] consumer/strategy.go @luther-siyuan https://github.com/apache/rocketmq-client-go/pull/141

- [ ] internal/client.go @luther-siyuan
- [ ] internal/route.go, internal/namesrv.go,  @cloes
- [ ] internal/request.go internal/request.go @cloes

- [ ] internal/utils @wenfengwang

**Comment by chxfantasy** [comment]
👍👍

**Comment by zacharyzhanghao** [comment]
awesome

**Comment by wolftankk** [comment]
GJ!

**Comment by vongosling** [comment]
@wenfengwang Do we need to continue opening this issue. I've seen we have released 2.0.0-rc1

**Comment by guanwenbogit** [comment]
目前只能支持ip地址么？

**Comment by ShannonDing** [comment]
> �目前只能支持ip地址么？

Both  IP and domain are supported. See #195
