### ISSUE TITLE
RocketMQ Go Client 2.0.0-alpha1 release Checklist

### ISSUE THREAD

**Issue by wenfengwang** [apache/rocketmq-client-go#54]
## Description
RocketMQ Go Client in pure go is coming soon, here are some checkpoint before release

## Docs
- [x] How to use
- [x] Examples

### MessageType
- [x] NormalMessage

### SendWith    
- [x] Sync
- [x] OneWay

## Consumer
- [x] Consuming With Push
- [x] Consuming With Concurrently
- [x] AllocateMessageQueueAveragely 

### MessageModel
- [x] CLUSTERING
- [x] BROADCASTING

### Other
- [x] Offset Sotre
- [x] Flow Control
- [x] Rebalance
- [x] ConsumeFromWhere
- [x] PersistAllConsumerOffset

## Common
- [x] Route Manage
- [x] CleanOfflineBroker 
- [x] HeartBeat

## Remote
- [x] API
    - [x] InvokeSync
    - [x] InvokeOneWay
- [x] Serialize
    - [x] JSON
    - [x] ROCKETMQ

**Comment by jerry-tao** [comment]
1. namesrv不支持多个配置 `127.0.0.1:9876;127.0.0.2;9876`
2. 不支持autoCreateTopic
3. 出现以上两个错误都panic，这样影响比较大，效果也不好，改为返回err更合理。

**Comment by wenfengwang** [comment]
@jerry-tao 
1. multiple namesrvs will be supported in alpha2.
2. `autoCreateTopic`  will not be  supported in future
3. I will optimize it before release

**Comment by hnlq715** [comment]
@wenfengwang 
shutdown支持一波就能试水了 😃

**Comment by wenfengwang** [comment]
@hnlq715 it will be supported in alpha2, please see https://github.com/apache/rocketmq-client-go/issues/75
