### ISSUE TITLE
2.0.0-alpha2 Roadmap

### ISSUE THREAD

**Issue by wenfengwang** [apache/rocketmq-client-go#75]
The alpha2 has been started, welcome anyone request for an `unassigned` item or have any contributions for us!

### Duration
6.27-7.14

### Target
1. refactor API, make implementation, basic data-struct and API have a separation 
2. improve stability of features are released in alpha1
3. add new features
4. enrich unit tests

### Bugfix
- [x] Missing Tag and Properties in Message  https://github.com/apache/rocketmq-client-go/issues/65, PR: https://github.com/apache/rocketmq-client-go/pull/94  @xujianhai666 
- [x] The timeout of RPC doesn't work @gaufung  PR: https://github.com/apache/rocketmq-client-go/pull/97
- [x] The InvokeAsync doesn't work @gaufung  https://github.com/apache/rocketmq-client-go/pull/97

### Optimization
- [x] refactor API @wenfengwang  https://github.com/apache/rocketmq-client-go/issues/93, PR1: https://github.com/apache/rocketmq-client-go/pull/82, PR2: https://github.com/apache/rocketmq-client-go/pull/103
- [x] implement shutdown @gaufung https://github.com/apache/rocketmq-client-go/pull/97
- [x] support context `unassigned` *postponed to alpha3*
- [x] change fatal to error in `start()` of producer and consumer @gaufung  https://github.com/apache/rocketmq-client-go/pull/107

### Feature
- [x] Support multiple NameServer @xujianhai666 https://github.com/apache/rocketmq-client-go/pull/96
- [x] Support PullConsumer @xujianhai666 https://github.com/apache/rocketmq-client-go/pull/106
- [x] Support SendAsync @xujianhai666 https://github.com/apache/rocketmq-client-go/pull/100
- [x] Support QueueSelector @xujianhai666 https://github.com/apache/rocketmq-client-go/pull/102
- [x] Support order message in PushConsumer @xujianhai666 https://github.com/apache/rocketmq-client-go/pull/115
- [x] Support Statistics of client @gaufung https://github.com/apache/rocketmq-client-go/pull/113
- [x] Support retry when consume failed in PushConsumer @xujianhai666 https://github.com/apache/rocketmq-client-go/pull/119/
- [x] Support Interceptor @xujianhai666 https://github.com/apache/rocketmq-client-go/issues/86
- [x] Support ACL @wenfengwang https://github.com/apache/rocketmq-client-go/pull/117

## Unit Test
- [x] package of remote @gaofeng
- [x] producer @xujianhai666 https://github.com/apache/rocketmq-client-go/pull/109
- [x] internal/route.go @luther-siyuan https://github.com/apache/rocketmq-client-go/pull/116
- [x] internal/client.go `unassigned`  *postponed to alpha3*

**Comment by tianshouzhi** [comment]
我们目前需要在生产环境使用PullConsumer，请问这个任务可以分配给我这边吗？

**Comment by wenfengwang** [comment]
@tianshouzhi certainly!

**Comment by wenfengwang** [comment]
The 2.0.0-alpha2 release note: https://github.com/apache/rocketmq-client-go/pull/121
